# Team Yaml
coverage:
  round: down
  precision: 2

# Repository Yaml
coverage:
  round: down
  range: 40..80
  
  ignore:
    - "tests/**/*.py"
    - "src/setup.py"
    - "src/plotting/*"

codecov:
  max_report_age: off

#fixes:
#  - "/usr/local/lib/**/dist-packages/pymoc/::src/modules/"