# Team Yaml
coverage:
  round: down
  precision: 2

# Repository Yaml
coverage:
  round: down
  range: 40..80
  
  ignore:
    - "examples/**/*.py"
    - "tests/**/*.py"
    - "setup.py"
    - "pymoc/plotting/*"

codecov:
  max_report_age: off
