version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    enabled: false
exclude_patterns:
  - "examples/**/*.py"
  - "tests/**/*.py"
  - "src/pymoc/plotting/*"
  - "src/**/__init__.py"
  - "setup.py"
  - "docs/*"
  - "Dockerfile*"
  - ".circleci/*"
  - ".coveragerc"
  - ".githooks/*"
  - ".gitignore"
  - ".style.yapf"
  - "LICENSE"
  - "MANIFEST"
  - "Makefile"
  - "cc-test-reporter"
  - "*.md"
  - "*.yml"
  - "*.html"
  - "*.pdf"