version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    enabled: false
exclude_patterns:
  - "examples/**/*.py"
  - "tests/**/*.py"
  - "pymoc/plotting/*"
  - "setup.py"